# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "burp_cms"
  s.version = "1.3.23"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darwin"]
  s.date = "2013-09-09"
  s.description = " A CMS that tries hard to not get in your way! "
  s.email = "darwin@bits2life.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Rakefile",
    "app/assets/images/burp/add-group-to-menu-1.png",
    "app/assets/images/burp/add-group-to-menu-2.png",
    "app/assets/images/burp/add-group-to-menu-3.png",
    "app/assets/images/burp/add-group-to-menu-4.png",
    "app/assets/images/burp/add-image-1.png",
    "app/assets/images/burp/add-image-2.jpg",
    "app/assets/images/burp/add-image-3.jpg",
    "app/assets/images/burp/add-image-4.jpg",
    "app/assets/images/burp/add-image-5.png",
    "app/assets/images/burp/add-link-to-group-1.png",
    "app/assets/images/burp/add-link-to-group-2.png",
    "app/assets/images/burp/add-link-to-group-3.png",
    "app/assets/images/burp/add-link-to-menu-1.png",
    "app/assets/images/burp/add-link-to-menu-2.png",
    "app/assets/images/burp/add-link-to-menu-3.png",
    "app/assets/images/burp/add-link-to-menu-4.png",
    "app/assets/images/burp/add-page-to-menu-1.png",
    "app/assets/images/burp/add-page-to-menu-2.png",
    "app/assets/images/burp/add-page-to-menu-3.png",
    "app/assets/images/burp/add-page-to-menu-4.png",
    "app/assets/images/burp/add-page-to-menu-5.png",
    "app/assets/images/burp/adding-a-page-1.png",
    "app/assets/images/burp/adding-a-page-2.png",
    "app/assets/images/burp/adding-a-page-3.png",
    "app/assets/images/burp/adding-a-page-4.png",
    "app/assets/images/burp/change-page-title-1.png",
    "app/assets/images/burp/change-page-title-2.png",
    "app/assets/images/burp/change-page-title-3.png",
    "app/assets/images/burp/change-page-title-4.png",
    "app/assets/images/burp/change-the-text-1.png",
    "app/assets/images/burp/change-the-text-2.png",
    "app/assets/images/burp/change-the-text-3.png",
    "app/assets/images/burp/enter-page-edit-mode-1.png",
    "app/assets/images/burp/enter-page-edit-mode-2.png",
    "app/assets/images/burp/enter-page-edit-mode-3.png",
    "app/assets/images/burp/enter-page-edit-mode-4.jpg",
    "app/assets/images/burp/img/glyphicons-halflings-white.png",
    "app/assets/images/burp/img/glyphicons-halflings.png",
    "app/assets/images/burp/move-link-to-bottom-of-menu-1.png",
    "app/assets/images/burp/move-link-to-bottom-of-menu-2.png",
    "app/assets/images/burp/move-link-to-bottom-of-menu-3.png",
    "app/assets/images/burp/remove-a-page-1.png",
    "app/assets/images/burp/remove-a-page-2.png",
    "app/assets/images/burp/remove-a-page-3.png",
    "app/assets/images/burp/remove-a-page-4.png",
    "app/assets/images/burp/remove-image-1.png",
    "app/assets/images/burp/remove-image-2.jpg",
    "app/assets/images/burp/remove-image-3.jpg",
    "app/assets/images/burp/remove-image-4.jpg",
    "app/assets/images/burp/remove-image-5.jpg",
    "app/assets/images/burp/remove-page-from-menu-1.png",
    "app/assets/images/burp/remove-page-from-menu-2.png",
    "app/assets/images/burp/remove-page-from-menu-3.png",
    "app/assets/images/burp/remove-page-from-menu-4.png",
    "app/assets/javascripts/burp/application.js",
    "app/assets/javascripts/burp/burp.js",
    "app/assets/javascripts/burp/cms_helper.js",
    "app/assets/javascripts/burp/edit-links.js",
    "app/assets/javascripts/burp/edit-page.js",
    "app/assets/javascripts/burp/form_popover.js",
    "app/assets/javascripts/burp/lib/bootstrap.min.js",
    "app/assets/javascripts/burp/lib/debug.js",
    "app/assets/javascripts/burp/lib/fileupload.js",
    "app/assets/javascripts/burp/lib/missing-restful-verbs.js",
    "app/assets/javascripts/burp/pages-drag-and-drop.js",
    "app/assets/packages/burp/editing.js",
    "app/assets/packages/burp/editing.less",
    "app/assets/packages/burp/editing/css/dropzone.css",
    "app/assets/packages/burp/editing/css/edit-content.less",
    "app/assets/packages/burp/editing/css/gallery.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/LICENSE.txt",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/keymap/emacs.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/keymap/vim.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/codemirror.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/codemirror.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/closetag.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/dialog.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/dialog.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/foldcode.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/formatting.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/javascript-hint.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/loadmode.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/match-highlighter.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/multiplex.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/overlay.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/pig-hint.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/runmode.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/search.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/searchcursor.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/simple-hint.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/lib/util/simple-hint.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/css/css.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/css/index.html",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/htmlembedded/htmlembedded.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/htmlembedded/index.html",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/htmlmixed/htmlmixed.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/htmlmixed/index.html",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/javascript/index.html",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/javascript/javascript.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/markdown/index.html",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/markdown/markdown.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/xml/index.html",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/mode/xml/xml.js",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/package.json",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/ambiance.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/blackboard.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/cobalt.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/eclipse.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/elegant.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/erlang-dark.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/lesser-dark.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/monokai.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/neat.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/night.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/rubyblue.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/vibrant-ink.css",
    "app/assets/packages/burp/editing/dep/CodeMirror-2.3/theme/xq-dark.css",
    "app/assets/packages/burp/editing/dep/FontAwesome/font/fontawesome-webfont.eot",
    "app/assets/packages/burp/editing/dep/FontAwesome/font/fontawesome-webfont.svg",
    "app/assets/packages/burp/editing/dep/FontAwesome/font/fontawesome-webfont.ttf",
    "app/assets/packages/burp/editing/dep/FontAwesome/font/fontawesome-webfont.woff",
    "app/assets/packages/burp/editing/dep/FontAwesome/less/font-awesome-ie7.less",
    "app/assets/packages/burp/editing/dep/FontAwesome/less/font-awesome.less",
    "app/assets/packages/burp/editing/js/admin-dock.js",
    "app/assets/packages/burp/editing/js/content-decorator.js",
    "app/assets/packages/burp/editing/js/jquery.html2markdown.js",
    "app/assets/packages/burp/editing/js/main.js",
    "app/assets/packages/burp/editing/js/markdown-fix.js",
    "app/assets/packages/burp/editing/js/marked.js",
    "app/assets/packages/gritter/README.markdown",
    "app/assets/packages/gritter/css/jquery.gritter.less",
    "app/assets/packages/gritter/gritter.js",
    "app/assets/packages/gritter/gritter.less",
    "app/assets/packages/gritter/images/gritter-light.png",
    "app/assets/packages/gritter/images/gritter-long.png",
    "app/assets/packages/gritter/images/gritter.png",
    "app/assets/packages/gritter/images/ie-spacer.gif",
    "app/assets/packages/gritter/images/trees.jpg",
    "app/assets/packages/gritter/index.html",
    "app/assets/packages/gritter/js/jquery.gritter.js",
    "app/assets/packages/gritter/js/jquery.gritter.min.js",
    "app/assets/stylesheets/burp/application.less",
    "app/assets/stylesheets/burp/bootstrap.less",
    "app/assets/stylesheets/burp/docs.less",
    "app/assets/stylesheets/burp/fileupload.less",
    "app/assets/stylesheets/burp/views/dnd-menu.less",
    "app/assets/stylesheets/burp/views/files/index.less",
    "app/assets/stylesheets/burp/views/pages/index.less",
    "app/assets/stylesheets/burp/views/static/help.less",
    "app/controllers/burp/application_controller.rb",
    "app/controllers/burp/catch_all_controller.rb",
    "app/controllers/burp/error_controller.rb",
    "app/controllers/burp/files_controller.rb",
    "app/controllers/burp/groups_controller.rb",
    "app/controllers/burp/links_controller.rb",
    "app/controllers/burp/menus_controller.rb",
    "app/controllers/burp/pages_controller.rb",
    "app/controllers/burp/static_controller.rb",
    "app/helpers/burp/application_helper.rb",
    "app/lib/burp/access.rb",
    "app/lib/burp/group.rb",
    "app/lib/burp/link.rb",
    "app/lib/burp/page.rb",
    "app/lib/burp/util.rb",
    "app/lib/burp/util/upload_handler.rb",
    "app/models/burp/file_model.rb",
    "app/models/burp/menu.rb",
    "app/models/burp/page_model.rb",
    "app/views/burp/files/index.html.erb",
    "app/views/burp/groups/edit.html.erb",
    "app/views/burp/links/edit.html.erb",
    "app/views/burp/menus/edit.html.erb",
    "app/views/burp/menus/index.html.erb",
    "app/views/burp/pages/edit.html.erb",
    "app/views/burp/pages/index.html.erb",
    "app/views/burp/static/help.html.erb",
    "app/views/burp/static/index.html.erb",
    "app/views/layouts/burp/application.html.erb",
    "config/cucumber.yml",
    "config/initializers/init.rb",
    "config/routes.rb",
    "lib/burp/capistrano.rb",
    "lib/burp/engine.rb",
    "lib/burp/version.rb",
    "lib/burp_cms.rb",
    "lib/tasks/burp_tasks.rake"
  ]
  s.homepage = "http://github.com/bjornblomqvist/burp"
  s.licenses = ["LGPL3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.6"
  s.summary = "A CMS that tries hard to not get in your way!"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-ui-rails>, [">= 0"])
      s.add_runtime_dependency(%q<less-rails>, [">= 0"])
      s.add_runtime_dependency(%q<mayi>, [">= 0"])
      s.add_runtime_dependency(%q<therubyracer>, [">= 0"])
      s.add_runtime_dependency(%q<bootstrap_forms>, [">= 0"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["~> 3.2"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<jquery-ui-rails>, [">= 0"])
      s.add_dependency(%q<less-rails>, [">= 0"])
      s.add_dependency(%q<mayi>, [">= 0"])
      s.add_dependency(%q<therubyracer>, [">= 0"])
      s.add_dependency(%q<bootstrap_forms>, [">= 0"])
      s.add_dependency(%q<term-ansicolor>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.2"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<jquery-ui-rails>, [">= 0"])
    s.add_dependency(%q<less-rails>, [">= 0"])
    s.add_dependency(%q<mayi>, [">= 0"])
    s.add_dependency(%q<therubyracer>, [">= 0"])
    s.add_dependency(%q<bootstrap_forms>, [">= 0"])
    s.add_dependency(%q<term-ansicolor>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.2"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

